development:
  adapter: postgresql
  username: webservice
  password: webservicec
  database: corpocaldas
  encoding: utf8
  pool: 5
  host: 200.58.206.186

dev_local:
  adapter: postgresql
  username: marco
  password: montes
  database: webservice
  encoding: utf8
  pool: 5

test:
  adapter: postgresql
  username: postgres
  password: postgres
  database: webservice_test
  
production:
  adapter: postgresql
  username: consultacorpo
  password: consultacorpo
  database: corpocaldas
  encoding: utf8
  pool: 5
  host: 200.58.206.186